services:
  db-vector:
    image: pgvector/pgvector:pg16
    container_name: gemini-vector-db
    restart: always
    environment:
      POSTGRES_USER: bulam
      POSTGRES_PASSWORD: your_secure_password
      POSTGRES_DB: gemini_history
    ports:
      - "5433:5432" # Le port 5432 étant déjà occupé, j'utilise le 5433.
    volumes:
      - pgvector_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bulam -d gemini_history"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgvector_data:
